services:
    php:
        container_name: ${APP_NAME}_php
        build:
            context: ./.docker/php
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - './:/var/www/html'

    # Web server
    web:
        image: nginx:alpine
        container_name: ${APP_NAME}_nginx
        working_dir: /var/www/html
        volumes:
            - './:/var/www/html'
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            # - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"

    # postgres:
    #     image: postgres:16.2-alpine3.19
    #     container_name: ${APP_NAME}_postgres
    #     restart:
    #         unless-stopped
    #     ports:
    #         - '5433:5432'
    #     volumes:
    #         - ./.docker/postgres-data:/var/lib/postgresql/data
    #     environment:
    #         POSTGRES_USER: '${DB_USERNAME}'
    #         POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    #         POSTGRES_DB: '${DB_DATABASE}'
    #         PGPASSWORD: '${DB_PASSWORD:-secret}'
    #     networks:
    #         - app

    # redis:
    #     image: 'redis:alpine'
    #     container_name: ${APP_NAME}_redis
    #     ports:
    #         - '${6378}:6379'
    #     volumes:
    #         - ./.docker/redis-data:/data
    #     networks:
    #         - app

    # laravel.test:
    #     build:
    #         context: ./docker/8.3
    #         dockerfile: Dockerfile
    #         args:
    #             WWWGROUP: '${WWWGROUP}'
    #     image: sail-8.3/app
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     ports:
    #         - '${APP_PORT:-80}:80'
    #         - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    #     environment:
    #         WWWUSER: '${WWWUSER}'
    #         LARAVEL_SAIL: 1
    #         XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    #         XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    #         IGNITION_LOCAL_SITES_PATH: '${PWD}'
    #     volumes:
    #         - '.:/var/www/html'
    #     networks:
    #         - sail
    #     depends_on:
    #         - pgsql
    #         - redis
    # pgsql:
    #     image: 'postgres:15'
    #     ports:
    #         - '${FORWARD_DB_PORT:-5432}:5432'
    #     environment:
    #         PGPASSWORD: '${DB_PASSWORD:-secret}'
    #         POSTGRES_DB: '${DB_DATABASE}'
    #         POSTGRES_USER: '${DB_USERNAME}'
    #         POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    #     volumes:
    #         - 'sail-pgsql:/var/lib/postgresql/data'
    #         - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - pg_isready
    #             - '-q'
    #             - '-d'
    #             - '${DB_DATABASE}'
    #             - '-U'
    #             - '${DB_USERNAME}'
    #         retries: 3
    #         timeout: 5s
#     redis:
#         image: 'redis:alpine'
#         ports:
#             - '${FORWARD_REDIS_PORT:-6379}:6379'
#         volumes:
#             - 'sail-redis:/data'
#         networks:
#             - sail
#         healthcheck:
#             test:
#                 - CMD
#                 - redis-cli
#                 - ping
#             retries: 3
#             timeout: 5s
# networks:
#     sail:
#         driver: bridge
# volumes:
#     sail-pgsql:
#         driver: local
#     sail-redis:
#         driver: local
