services:
    postgres:
        image: postgres:16.2-alpine3.19
        container_name: ${APP_NAME}_postgres
        volumes:
            - .docker/postgres/data:/var/lib/postgres
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            PGPASSWORD: '${DB_PASSWORD}'
        networks:
            - app
        healthcheck:
            test: ["CMD", "pg_isready", '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
            timeout: 5s
            retries: 3

    redis:
        image: redis:alpine
        container_name: ${APP_NAME}_redis
        volumes:
            - .docker/redis/data:/data
        networks:
            - app
        healthcheck:
            test: ["CMD", "redis-cli", 'ping']
            retries: 3
            timeout: 5s

    # Web server
    web:
        image: nginx_img
        container_name: ${APP_NAME}_nginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app

    php:
        image: php_img
        container_name: ${APP_NAME}_php
        networks:
            - app
        depends_on:
            - postgres

networks:
    app:
        driver: bridge
